#!/bin/bash
set -e

PACKAGES_VOLUME="python-sandbox-packages"
SITE_PACKAGES="/usr/local/lib/python3.14/site-packages"
IMAGE="python-sandbox"

DOCKER_OPTS=(--rm -i -v "$(pwd):/work/pwd" -v "$PACKAGES_VOLUME:$SITE_PACKAGES")

# オプションを収集
PIP_PACKAGES=()
DIR_COUNT=0
while [[ "$1" == --* ]]; do
  case "$1" in
    --pip)
      shift
      PIP_PACKAGES+=("$1")
      shift
      ;;
    --dir)
      shift
      DIR_COUNT=$((DIR_COUNT + 1))
      DOCKER_OPTS+=(-v "$1:/work/dir${DIR_COUNT}")
      shift
      ;;
    *)
      break
      ;;
  esac
done

if [[ ${#PIP_PACKAGES[@]} -gt 0 ]]; then
  PIP_CMD="pip install -q ${PIP_PACKAGES[*]} &&"
else
  PIP_CMD=""
fi

if [[ $# -gt 0 ]]; then
  # ファイル実行
  docker run "${DOCKER_OPTS[@]}" "$IMAGE" bash -c "$PIP_CMD python \$@" -- "$@"
else
  # 標準入力
  docker run "${DOCKER_OPTS[@]}" "$IMAGE" bash -c "$PIP_CMD python -"
fi
